"""Dataset adapters that convert source formats into canonical pieces."""

from music_critic.adapters.dilemmadata import (
    DILEMMADATA_ACCEPTANCE_REPORT_VERSION,
    DILEMMADATA_AN_RECORD_COUNT,
    DILEMMADATA_ADAPTER_VERSION,
    DILEMMADATA_CONTENT_FINGERPRINT,
    DILEMMADATA_CORPUS_IDENTITY_VERSION,
    DILEMMADATA_DATASET_NAME,
    DILEMMADATA_DLC_RECORD_COUNT,
    DILEMMADATA_GROUPING_VERSION,
    DILEMMADATA_INSTALLATION_FILE_COUNT,
    DILEMMADATA_PRIMARY_RECORD_COUNT,
    DILEMMADATA_PRODUCTION_MANIFEST_VERSION,
    DILEMMADATA_RAW_PROJECTION_VERSION,
    DILEMMADATA_RAW_TARGET_ALIGNMENT_EVIDENCE_VERSION,
    DILEMMADATA_RECORD_BINDING_VERSION,
    DILEMMADATA_RELEASE_COMMIT,
    DILEMMADATA_RELEASE_VERSION,
    DilemmadataAccepted,
    DilemmadataAdapterConfig,
    DilemmadataAdapterError,
    DilemmadataConversionError,
    DilemmadataConversionResult,
    DilemmadataConversionStatistics,
    DilemmadataCorpusDiscovery,
    DilemmadataCorpusIdentity,
    DilemmadataCorpusIdentityError,
    DilemmadataCorpusIssue,
    DilemmadataCorpusRecord,
    DilemmadataQuarantine,
    DilemmadataRawTargetAlignmentEvidence,
    DilemmadataSourceRowBinding,
    convert_dilemmadata_record,
    dilemmadata_raw_source_value_fields,
    discover_dilemmadata_corpus,
    iter_dilemmadata_corpus,
    reconstruct_dilemmadata_alignment_evidence,
    validate_dilemmadata_alignment_evidence,
    validate_dilemmadata_record_binding,
)
from music_critic.adapters.hooktheory import (
    HookTheoryAdapterConfig,
    HookTheoryAdapterError,
    convert_hooktheory_record,
    load_hooktheory_piece,
)
from music_critic.adapters.midi import (
    MidiAdapterConfig,
    MidiAdapterError,
    load_midi_piece,
)
from music_critic.adapters.pop909_cl import (
    POP909_CL_ADAPTER_VERSION,
    POP909_CL_ANOMALY_FINGERPRINT,
    POP909_CL_ANOMALY_FINGERPRINT_V1,
    POP909_CL_CONTENT_FINGERPRINT,
    POP909_CL_DATASET_NAME,
    POP909_CL_TARGET_SEMANTICS_VERSION,
    POP909_CL_TASKS,
    Pop909ClAccepted,
    Pop909ClAdapterConfig,
    Pop909ClAdapterError,
    Pop909ClConversionError,
    Pop909ClConversionResult,
    Pop909ClCorpusDiscovery,
    Pop909ClCorpusIdentity,
    Pop909ClCorpusIdentityError,
    Pop909ClCorpusRecord,
    Pop909ClExpectedTargetAbsence,
    Pop909ClQuarantine,
    convert_pop909_cl_file,
    discover_pop909_cl_corpus,
    inspect_pop909_cl_instruments,
    iter_pop909_cl_corpus,
    pop909_cl_source_group_id,
    pop909_cl_piece_id,
    pop909_cl_raw_input_group_id,
    pop909_lineage_group_id,
    project_pop909_cl_score_bytes,
)


_DILEMMADATA_TARGET_EXPORTS = frozenset(
    {
        "DILEMMADATA_TARGET_ADAPTER_VERSION",
        "DILEMMADATA_TARGET_AUDIT_MANIFEST_VERSION",
        "DILEMMADATA_TARGET_AUDIT_REPORT_VERSION",
        "DILEMMADATA_TARGET_METADATA_VERSION",
        "DILEMMADATA_TARGET_SIDECAR_VERSION",
        "DilemmadataTargetAccepted",
        "DilemmadataTargetAdapterConfig",
        "DilemmadataTargetAdapterError",
        "DilemmadataTargetConversionResult",
        "DilemmadataTargetFamilyStatistics",
        "DilemmadataTargetMetadata",
        "DilemmadataTargetMetadataIndex",
        "DilemmadataTargetQuarantine",
        "DilemmadataTargetStatistics",
        "build_dilemmadata_target_sidecar",
        "convert_dilemmadata_target_sidecar",
        "iter_dilemmadata_target_sidecars",
        "load_dilemmadata_target_metadata_index",
    }
)


def __getattr__(name: str):
    """Load the target-only adapter lazily to keep worker imports acyclic."""

    if name not in _DILEMMADATA_TARGET_EXPORTS:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    from music_critic.adapters import dilemmadata_targets

    value = getattr(dilemmadata_targets, name)
    globals()[name] = value
    return value

__all__ = [
    "DILEMMADATA_ACCEPTANCE_REPORT_VERSION",
    "DILEMMADATA_AN_RECORD_COUNT",
    "DILEMMADATA_ADAPTER_VERSION",
    "DILEMMADATA_CONTENT_FINGERPRINT",
    "DILEMMADATA_CORPUS_IDENTITY_VERSION",
    "DILEMMADATA_DATASET_NAME",
    "DILEMMADATA_DLC_RECORD_COUNT",
    "DILEMMADATA_GROUPING_VERSION",
    "DILEMMADATA_INSTALLATION_FILE_COUNT",
    "DILEMMADATA_PRIMARY_RECORD_COUNT",
    "DILEMMADATA_PRODUCTION_MANIFEST_VERSION",
    "DILEMMADATA_RAW_PROJECTION_VERSION",
    "DILEMMADATA_RAW_TARGET_ALIGNMENT_EVIDENCE_VERSION",
    "DILEMMADATA_RECORD_BINDING_VERSION",
    "DILEMMADATA_RELEASE_COMMIT",
    "DILEMMADATA_RELEASE_VERSION",
    "DILEMMADATA_TARGET_ADAPTER_VERSION",
    "DILEMMADATA_TARGET_AUDIT_MANIFEST_VERSION",
    "DILEMMADATA_TARGET_AUDIT_REPORT_VERSION",
    "DILEMMADATA_TARGET_METADATA_VERSION",
    "DILEMMADATA_TARGET_SIDECAR_VERSION",
    "DilemmadataAccepted",
    "DilemmadataAdapterConfig",
    "DilemmadataAdapterError",
    "DilemmadataConversionError",
    "DilemmadataConversionResult",
    "DilemmadataConversionStatistics",
    "DilemmadataCorpusDiscovery",
    "DilemmadataCorpusIdentity",
    "DilemmadataCorpusIdentityError",
    "DilemmadataCorpusIssue",
    "DilemmadataCorpusRecord",
    "DilemmadataQuarantine",
    "DilemmadataRawTargetAlignmentEvidence",
    "DilemmadataSourceRowBinding",
    "DilemmadataTargetAccepted",
    "DilemmadataTargetAdapterConfig",
    "DilemmadataTargetAdapterError",
    "DilemmadataTargetConversionResult",
    "DilemmadataTargetFamilyStatistics",
    "DilemmadataTargetMetadata",
    "DilemmadataTargetMetadataIndex",
    "DilemmadataTargetQuarantine",
    "DilemmadataTargetStatistics",
    "HookTheoryAdapterConfig",
    "HookTheoryAdapterError",
    "MidiAdapterConfig",
    "MidiAdapterError",
    "POP909_CL_ADAPTER_VERSION",
    "POP909_CL_ANOMALY_FINGERPRINT",
    "POP909_CL_ANOMALY_FINGERPRINT_V1",
    "POP909_CL_CONTENT_FINGERPRINT",
    "POP909_CL_DATASET_NAME",
    "POP909_CL_TARGET_SEMANTICS_VERSION",
    "POP909_CL_TASKS",
    "Pop909ClAccepted",
    "Pop909ClAdapterConfig",
    "Pop909ClAdapterError",
    "Pop909ClConversionError",
    "Pop909ClConversionResult",
    "Pop909ClCorpusDiscovery",
    "Pop909ClCorpusIdentity",
    "Pop909ClCorpusIdentityError",
    "Pop909ClCorpusRecord",
    "Pop909ClExpectedTargetAbsence",
    "Pop909ClQuarantine",
    "convert_hooktheory_record",
    "convert_dilemmadata_record",
    "dilemmadata_raw_source_value_fields",
    "build_dilemmadata_target_sidecar",
    "convert_dilemmadata_target_sidecar",
    "convert_pop909_cl_file",
    "discover_pop909_cl_corpus",
    "discover_dilemmadata_corpus",
    "inspect_pop909_cl_instruments",
    "iter_pop909_cl_corpus",
    "iter_dilemmadata_corpus",
    "reconstruct_dilemmadata_alignment_evidence",
    "iter_dilemmadata_target_sidecars",
    "load_dilemmadata_target_metadata_index",
    "load_hooktheory_piece",
    "load_midi_piece",
    "pop909_cl_source_group_id",
    "pop909_cl_piece_id",
    "pop909_cl_raw_input_group_id",
    "pop909_lineage_group_id",
    "project_pop909_cl_score_bytes",
    "validate_dilemmadata_alignment_evidence",
    "validate_dilemmadata_record_binding",
]
