"""Versioned theory-target and future mixed-source batching contracts."""

from music_critic.tasks.alignment import (
    ALIGNMENT_CONFLICT_DIAGNOSTIC,
    AlignedTargetFamily,
    AlignedTargetRow,
    TargetAlignmentError,
    align_sample_targets,
)
from music_critic.tasks.collator import (
    CollatorBenchmark,
    benchmark_multisource_collator,
    collate_multisource_samples,
    tensorize_aligned_targets,
)
from music_critic.tasks.encoding import (
    TARGET_ENCODINGS,
    TARGET_ENCODING_BY_TASK,
    TARGET_ENCODING_REGISTRY_VERSION,
    EncodingDType,
    EncodingKind,
    TargetEncodingSpec,
    dumps_target_encoding_contract,
    target_encoding_contract_dict,
    target_encoding_contract_fingerprint,
)
from music_critic.tasks.multisource import (
    BatchStatistics,
    BatchTarget,
    DatasetSamplingWeight,
    GroupAssignment,
    MultiSourceBatch,
    MultiSourceContractError,
    MultiSourceSample,
    SampleTarget,
    TargetDiagnostic,
    TargetRowProvenance,
    TaskBatchStatistics,
    TaskAvailability,
    build_multisource_sample,
    deterministic_group_order,
    validate_group_assignments,
)
from music_critic.tasks.ontology import (
    CROSSWALKS,
    CROSSWALK_BY_ID,
    TARGET_FAMILIES,
    TARGET_FAMILY_BY_ID,
    TARGET_ONTOLOGY_VERSION,
    AlignmentPolicy,
    CandidateAlignmentRule,
    CrosswalkSpec,
    CrosswalkStatus,
    TargetFamilySpec,
    dumps_ontology_contract,
    ontology_contract_dict,
    ontology_contract_fingerprint,
)


__all__ = [
    "ALIGNMENT_CONFLICT_DIAGNOSTIC",
    "AlignedTargetFamily",
    "AlignedTargetRow",
    "AlignmentPolicy",
    "BatchStatistics",
    "BatchTarget",
    "CROSSWALKS",
    "CROSSWALK_BY_ID",
    "CandidateAlignmentRule",
    "CrosswalkSpec",
    "CrosswalkStatus",
    "CollatorBenchmark",
    "DatasetSamplingWeight",
    "EncodingDType",
    "EncodingKind",
    "GroupAssignment",
    "MultiSourceBatch",
    "MultiSourceContractError",
    "MultiSourceSample",
    "SampleTarget",
    "TARGET_FAMILIES",
    "TARGET_FAMILY_BY_ID",
    "TARGET_ENCODINGS",
    "TARGET_ENCODING_BY_TASK",
    "TARGET_ENCODING_REGISTRY_VERSION",
    "TARGET_ONTOLOGY_VERSION",
    "TargetFamilySpec",
    "TargetEncodingSpec",
    "TargetAlignmentError",
    "TargetDiagnostic",
    "TargetRowProvenance",
    "TaskBatchStatistics",
    "TaskAvailability",
    "align_sample_targets",
    "benchmark_multisource_collator",
    "build_multisource_sample",
    "collate_multisource_samples",
    "deterministic_group_order",
    "dumps_ontology_contract",
    "dumps_target_encoding_contract",
    "ontology_contract_dict",
    "ontology_contract_fingerprint",
    "target_encoding_contract_dict",
    "target_encoding_contract_fingerprint",
    "tensorize_aligned_targets",
    "validate_group_assignments",
]
